[variables]
NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22", "pnpm"]

[phases.install]
cmds = ["corepack enable", "corepack pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["corepack pnpm --filter @corens/api... build"]

[start]
cmd = "corepack pnpm --filter @corens/api start"
